trigger:
  branches:
    include:
      - main  # Jab bhi main branch me code push ho, pipeline chale

pool:
  name: skp-agent  # Tumhara self-hosted agent ka naam

jobs:
- job: terraform_job
  displayName: 'Terraform Init and Plan Job'
  steps:

  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'first_connection'
      backendAzureRmStorageAccountName: 'stggaurav777'
      backendAzureRmContainerName: 'gauravcontainer'
      backendAzureRmKey: 'skp.tfstate'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'first_connection'
    