trigger:
  branches:
    include:
      - main

pool:
  name: skp-agent

jobs:
  - job: terraform_job
    displayName: Terraform Flow

    steps:
    - task: TerraformInstaller@1
      displayName: Install TF
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'first_connection'
        backendAzureRmStorageAccountName: 'stggaurav777'
        backendAzureRmContainerName: 'gauravcontainer'
        backendAzureRmKey: 'skp.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
     
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'first_connection'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'first_connection'
