trigger:
  branches:
    include:
      - main

pool:
  name: skp-agent

jobs:
- job: terraform_job
  displayName: 'Terraform Init Job'
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'first_connection'
      backendAzureRmStorageAccountName: 'stggaurav777'
      backendAzureRmContainerName: 'gauravcontainer'
      backendAzureRmKey: 'skp.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'first_connection'